// Real English Placement Test Questions Database
const allQuestions = [
    // ==================== GRAMMAR (20 Questions) ====================
    {
        type: 'grammar',
        question: 'If I ____ known about the meeting, I would have attended.',
        options: ['had', 'have', 'was', 'would have'],
        correctAnswer: 0,
    },
    {
        type: 'grammar',
        question: 'She has been working here ____ five years.',
        options: ['since', 'for', 'during', 'while'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'The book ____ by the author last year was very successful.',
        options: ['writing', 'written', 'write', 'writes'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'Neither John nor Mary ____ interested in the project.',
        options: ['are', 'is', 'has', 'have'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'I wish I ____ speak French fluently.',
        options: ['could', 'can', 'would', 'might'],
        correctAnswer: 0,
    },
    {
        type: 'grammar',
        question: 'By next month, we ____ the project.',
        options: ['will complete', 'will have completed', 'complete', 'have completed'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'She insisted ____ paying for dinner.',
        options: ['on', 'in', 'at', 'to'],
        correctAnswer: 0,
    },
    {
        type: 'grammar',
        question: 'The more you practice, ____ you become.',
        options: ['the best', 'better', 'the better', 'best'],
        correctAnswer: 2,
    },
    {
        type: 'grammar',
        question: 'He would rather ____ at home than go out.',
        options: ['to stay', 'stay', 'staying', 'stayed'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'I\'m not used to ____ up so early.',
        options: ['wake', 'waking', 'woke', 'to wake'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'Unless you ____ your homework, you can\'t go out.',
        options: ['finish', 'finished', 'will finish', 'have finished'],
        correctAnswer: 0,
    },
    {
        type: 'grammar',
        question: 'The children ____ playing in the park when it started raining.',
        options: ['were', 'had been', 'have been', 'are'],
        correctAnswer: 0,
    },
    {
        type: 'grammar',
        question: 'It\'s time you ____ about your future.',
        options: ['think', 'thought', 'are thinking', 'have thought'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'They\'ve promised ____ us the money by Friday.',
        options: ['sending', 'to send', 'send', 'sent'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'Had I realized the consequences, I ____ done it.',
        options: ['would have', 'wouldn\'t have', 'won\'t have', 'haven\'t'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'Despite ____ tired, she continued working.',
        options: ['being', 'be', 'been', 'to be'],
        correctAnswer: 0,
    },
    {
        type: 'grammar',
        question: 'The report must ____ before the deadline.',
        options: ['to submit', 'submit', 'be submitted', 'submitted'],
        correctAnswer: 2,
    },
    {
        type: 'grammar',
        question: 'He acts as if he ____ the company.',
        options: ['owns', 'owned', 'would own', 'have owned'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'No sooner had she arrived ____ it started to rain.',
        options: ['then', 'than', 'when', 'as'],
        correctAnswer: 2,
    },
    {
        type: 'grammar',
        question: 'She couldn\'t help ____ about the situation.',
        options: ['to worry', 'worry', 'worrying', 'worried'],
        correctAnswer: 2,
    },

    // ==================== VOCABULARY (15 Questions) ====================
    {
        type: 'vocabulary',
        question: 'What is the synonym of "benevolent"?',
        options: ['mean', 'kind', 'lazy', 'brave'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'What is the antonym of "abundant"?',
        options: ['plentiful', 'scarce', 'plenty', 'sufficient'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'To "procrastinate" means to:',
        options: ['work hard', 'delay doing something', 'finish quickly', 'plan carefully'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'The company decided to ____ from the project due to financial issues.',
        options: ['withdraw', 'involve', 'engage', 'participate'],
        correctAnswer: 0,
    },
    {
        type: 'vocabulary',
        question: 'What is a synonym for "abundant"?',
        options: ['scarce', 'plentiful', 'minimal', 'rare'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'He decided to "call off" the meeting. This means to:',
        options: ['postpone', 'cancel', 'attend', 'organize'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'The speech was so ____ that everyone was moved to tears.',
        options: ['mundane', 'poignant', 'superficial', 'trivial'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'Which phrasal verb means "to improve"?',
        options: ['get down', 'get along', 'get over', 'get ahead'],
        correctAnswer: 3,
    },
    {
        type: 'vocabulary',
        question: '"To ameliorate" means to:',
        options: ['worsen', 'improve', 'ignore', 'delay'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'The film was criticized for being too ____ and lacking depth.',
        options: ['profound', 'superficial', 'complex', 'meaningful'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'To "put up with" someone means to ____ them.',
        options: ['punish', 'tolerate', 'help', 'promote'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'Which word means the opposite of "eloquent"?',
        options: ['articulate', 'inarticulate', 'fluent', 'expressive'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'Her ____ attitude towards life made her popular among friends.',
        options: ['pessimistic', 'cynical', 'optimistic', 'gloomy'],
        correctAnswer: 2,
    },
    {
        type: 'vocabulary',
        question: 'To "give up" means to:',
        options: ['offer', 'surrender', 'continue', 'begin'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'The ____ of the ancient civilization amazed archaeologists.',
        options: ['destruction', 'legacy', 'absence', 'poverty'],
        correctAnswer: 1,
    },

    // ==================== READING (10 Questions) ====================
    {
        type: 'reading',
        passage: 'The Amazon rainforest, often referred to as the "lungs of the Earth," covers approximately 5.5 million square kilometers across nine countries. It is home to about 10% of all species on Earth, with an estimated 390 billion individual trees representing about 16,000 species. The rainforest plays a crucial role in regulating the Earth\'s climate by storing vast amounts of carbon and producing approximately 20% of the world\'s oxygen. However, deforestation threatens this vital ecosystem. Scientists estimate that approximately 137 species of plants, animals, and insects go extinct every single day due to rainforest destruction. Indigenous communities have lived in harmony with the Amazon for thousands of years and possess invaluable knowledge about the forest\'s biodiversity and sustainable practices. Protecting the rainforest is essential not only for preserving biodiversity but also for combating climate change and maintaining the ecological balance of our planet.',
        question: 'What is the primary function of the Amazon rainforest mentioned in the passage?',
        options: ['To provide natural resources for international trade', 'To act as the "lungs of the Earth" and regulate climate', 'To serve as a military base', 'To generate electricity'],
        correctAnswer: 1,
    },
    {
        type: 'reading',
        passage: 'The Amazon rainforest, often referred to as the "lungs of the Earth," covers approximately 5.5 million square kilometers across nine countries. It is home to about 10% of all species on Earth, with an estimated 390 billion individual trees representing about 16,000 species. The rainforest plays a crucial role in regulating the Earth\'s climate by storing vast amounts of carbon and producing approximately 20% of the world\'s oxygen. However, deforestation threatens this vital ecosystem. Scientists estimate that approximately 137 species of plants, animals, and insects go extinct every single day due to rainforest destruction. Indigenous communities have lived in harmony with the Amazon for thousands of years and possess invaluable knowledge about the forest\'s biodiversity and sustainable practices. Protecting the rainforest is essential not only for preserving biodiversity but also for combating climate change and maintaining the ecological balance of our planet.',
        question: 'How many species become extinct daily according to the passage?',
        options: ['About 100', 'About 137', 'About 500', 'About 1000'],
        correctAnswer: 1,
    },
    {
        type: 'reading',
        passage: 'The Amazon rainforest, often referred to as the "lungs of the Earth," covers approximately 5.5 million square kilometers across nine countries. It is home to about 10% of all species on Earth, with an estimated 390 billion individual trees representing about 16,000 species. The rainforest plays a crucial role in regulating the Earth\'s climate by storing vast amounts of carbon and producing approximately 20% of the world\'s oxygen. However, deforestation threatens this vital ecosystem. Scientists estimate that approximately 137 species of plants, animals, and insects go extinct every single day due to rainforest destruction. Indigenous communities have lived in harmony with the Amazon for thousands of years and possess invaluable knowledge about the forest\'s biodiversity and sustainable practices. Protecting the rainforest is essential not only for preserving biodiversity but also for combating climate change and maintaining the ecological balance of our planet.',
        question: 'What role do indigenous communities play in the Amazon?',
        options: ['They exploit the forest\'s resources', 'They have lived in harmony with the forest and possess valuable conservation knowledge', 'They are responsible for deforestation', 'They study the forest only'],
        correctAnswer: 1,
    },
    {
        type: 'reading',
        passage: 'The Amazon rainforest, often referred to as the "lungs of the Earth," covers approximately 5.5 million square kilometers across nine countries. It is home to about 10% of all species on Earth, with an estimated 390 billion individual trees representing about 16,000 species. The rainforest plays a crucial role in regulating the Earth\'s climate by storing vast amounts of carbon and producing approximately 20% of the world\'s oxygen. However, deforestation threatens this vital ecosystem. Scientists estimate that approximately 137 species of plants, animals, and insects go extinct every single day due to rainforest destruction. Indigenous communities have lived in harmony with the Amazon for thousands of years and possess invaluable knowledge about the forest\'s biodiversity and sustainable practices. Protecting the rainforest is essential not only for preserving biodiversity but also for combating climate change and maintaining the ecological balance of our planet.',
        question: 'Why is protecting the rainforest important for climate change?',
        options: ['It produces oxygen', 'It prevents hurricanes', 'It acts as a carbon sink and stores carbon', 'It regulates ocean temperatures'],
        correctAnswer: 2,
    },
    {
        type: 'reading',
        passage: 'The Amazon rainforest, often referred to as the "lungs of the Earth," covers approximately 5.5 million square kilometers across nine countries. It is home to about 10% of all species on Earth, with an estimated 390 billion individual trees representing about 16,000 species. The rainforest plays a crucial role in regulating the Earth\'s climate by storing vast amounts of carbon and producing approximately 20% of the world\'s oxygen. However, deforestation threatens this vital ecosystem. Scientists estimate that approximately 137 species of plants, animals, and insects go extinct every single day due to rainforest destruction. Indigenous communities have lived in harmony with the Amazon for thousands of years and possess invaluable knowledge about the forest\'s biodiversity and sustainable practices. Protecting the rainforest is essential not only for preserving biodiversity but also for combating climate change and maintaining the ecological balance of our planet.',
        question: 'What percentage of Earth\'s species live in the Amazon?',
        options: ['5%', '10%', '15%', '20%'],
        correctAnswer: 1,
    },
    {
        type: 'reading',
        passage: 'Artificial Intelligence (AI) is rapidly transforming industries worldwide. In healthcare, AI algorithms can now detect certain cancers more accurately than human radiologists. In finance, machine learning models analyze market trends and make investment recommendations. In education, AI tutoring systems personalize learning experiences for students. In manufacturing, robots powered by AI optimize production processes and reduce human error. However, rapid AI advancement raises important ethical questions about data privacy, algorithmic bias, job displacement, and the need for responsible development. Experts argue that strong regulations and ethical frameworks are essential to ensure AI benefits society while minimizing potential harms. The future of AI depends not only on technological innovation but also on responsible development and governance.',
        question: 'In healthcare, what advantage do AI algorithms have over human radiologists?',
        options: ['They are cheaper', 'They work faster', 'They can detect certain cancers more accurately', 'They require less training'],
        correctAnswer: 2,
    },
    {
        type: 'reading',
        passage: 'Artificial Intelligence (AI) is rapidly transforming industries worldwide. In healthcare, AI algorithms can now detect certain cancers more accurately than human radiologists. In finance, machine learning models analyze market trends and make investment recommendations. In education, AI tutoring systems personalize learning experiences for students. In manufacturing, robots powered by AI optimize production processes and reduce human error. However, rapid AI advancement raises important ethical questions about data privacy, algorithmic bias, job displacement, and the need for responsible development. Experts argue that strong regulations and ethical frameworks are essential to ensure AI benefits society while minimizing potential harms. The future of AI depends not only on technological innovation but also on responsible development and governance.',
        question: 'According to the passage, which is NOT mentioned as an application of AI?',
        options: ['Healthcare', 'Finance', 'Education', 'Agriculture'],
        correctAnswer: 3,
    },
    {
        type: 'reading',
        passage: 'Artificial Intelligence (AI) is rapidly transforming industries worldwide. In healthcare, AI algorithms can now detect certain cancers more accurately than human radiologists. In finance, machine learning models analyze market trends and make investment recommendations. In education, AI tutoring systems personalize learning experiences for students. In manufacturing, robots powered by AI optimize production processes and reduce human error. However, rapid AI advancement raises important ethical questions about data privacy, algorithmic bias, job displacement, and the need for responsible development. Experts argue that strong regulations and ethical frameworks are essential to ensure AI benefits society while minimizing potential harms. The future of AI depends not only on technological innovation but also on responsible development and governance.',
        question: 'What are the main ethical concerns raised about AI?',
        options: ['It\'s too expensive', 'Data privacy, algorithmic bias, and job displacement', 'It\'s not effective enough', 'It\'s only useful for large companies'],
        correctAnswer: 1,
    },
    {
        type: 'reading',
        passage: 'Artificial Intelligence (AI) is rapidly transforming industries worldwide. In healthcare, AI algorithms can now detect certain cancers more accurately than human radiologists. In finance, machine learning models analyze market trends and make investment recommendations. In education, AI tutoring systems personalize learning experiences for students. In manufacturing, robots powered by AI optimize production processes and reduce human error. However, rapid AI advancement raises important ethical questions about data privacy, algorithmic bias, job displacement, and the need for responsible development. Experts argue that strong regulations and ethical frameworks are essential to ensure AI benefits society while minimizing potential harms. The future of AI depends not only on technological innovation but also on responsible development and governance.',
        question: 'What is essential for AI\'s positive future according to experts?',
        options: ['Eliminating all regulations', 'Stopping AI development', 'Strong regulations and ethical frameworks', 'Using AI only in healthcare'],
        correctAnswer: 2,
    },
    {
        type: 'reading',
        passage: 'Artificial Intelligence (AI) is rapidly transforming industries worldwide. In healthcare, AI algorithms can now detect certain cancers more accurately than human radiologists. In finance, machine learning models analyze market trends and make investment recommendations. In education, AI tutoring systems personalize learning experiences for students. In manufacturing, robots powered by AI optimize production processes and reduce human error. However, rapid AI advancement raises important ethical questions about data privacy, algorithmic bias, job displacement, and the need for responsible development. Experts argue that strong regulations and ethical frameworks are essential to ensure AI benefits society while minimizing potential harms. The future of AI depends not only on technological innovation but also on responsible development and governance.',
        question: 'What does the passage suggest about the future of AI?',
        options: ['It depends only on technological innovation', 'It depends on both innovation and responsible development', 'AI will not be used in the future', 'Only wealthy countries will benefit from AI'],
        correctAnswer: 1,
    },

    // ==================== WRITING (1 Task) ====================
    {
        type: 'writing',
        question: 'Write an essay (80-120 words) on the following topic:\n\n"How has technology changed the way we communicate?"\n\nYour essay should include:\n• How communication has changed from the past\n• Benefits of modern communication technology\n• Any challenges or concerns\n• Your personal opinion\n\nWrite clearly and use complete sentences.',
        options: [],
        correctAnswer: -1,
    },
];
