// Real English Placement Test Questions Database
const allQuestions = [
    // ==================== GRAMMAR (20 Questions) ====================
    {
        type: 'grammar',
        question: 'If I ____ known about the meeting, I would have attended.',
        options: ['had', 'have', 'was', 'would have'],
        correctAnswer: 0,
    },
    {
        type: 'grammar',
        question: 'She has been working here ____ five years.',
        options: ['since', 'for', 'during', 'while'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'The book ____ by the author last year was very successful.',
        options: ['writing', 'written', 'write', 'writes'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'Neither John nor Mary ____ interested in the project.',
        options: ['are', 'is', 'has', 'have'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'I wish I ____ speak French fluently.',
        options: ['could', 'can', 'would', 'might'],
        correctAnswer: 0,
    },
    {
        type: 'grammar',
        question: 'By next month, we ____ the project.',
        options: ['will complete', 'will have completed', 'complete', 'have completed'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'She insisted ____ paying for dinner.',
        options: ['on', 'in', 'at', 'to'],
        correctAnswer: 0,
    },
    {
        type: 'grammar',
        question: 'The more you practice, ____ you become.',
        options: ['the best', 'better', 'the better', 'best'],
        correctAnswer: 2,
    },
    {
        type: 'grammar',
        question: 'He would rather ____ at home than go out.',
        options: ['to stay', 'stay', 'staying', 'stayed'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'I\\'m not used to ____ up so early.',
        options: ['wake', 'waking', 'woke', 'to wake'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'Unless you ____ your homework, you can\\'t go out.',
        options: ['finish', 'finished', 'will finish', 'have finished'],
        correctAnswer: 0,
    },
    {
        type: 'grammar',
        question: 'The children ____ playing in the park when it started raining.',
        options: ['were', 'had been', 'have been', 'are'],
        correctAnswer: 0,
    },
    {
        type: 'grammar',
        question: 'It\\'s time you ____ about your future.',
        options: ['think', 'thought', 'are thinking', 'have thought'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'They\\'ve promised ____ us the money by Friday.',
        options: ['sending', 'to send', 'send', 'sent'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'Had I realized the consequences, I ____ done it.',
        options: ['would have', 'wouldn\\'t have', 'won\\'t have', 'haven\\'t'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'Despite ____ tired, she continued working.',
        options: ['being', 'be', 'been', 'to be'],
        correctAnswer: 0,
    },
    {
        type: 'grammar',
        question: 'The report must ____ before the deadline.',
        options: ['to submit', 'submit', 'be submitted', 'submitted'],
        correctAnswer: 2,
    },
    {
        type: 'grammar',
        question: 'He acts as if he ____ the company.',
        options: ['owns', 'owned', 'would own', 'have owned'],
        correctAnswer: 1,
    },
    {
        type: 'grammar',
        question: 'No sooner had she arrived ____ it started to rain.',
        options: ['then', 'than', 'when', 'as'],
        correctAnswer: 2,
    },
    {
        type: 'grammar',
        question: 'She couldn\\'t help ____ about the situation.',
        options: ['to worry', 'worry', 'worrying', 'worried'],
        correctAnswer: 2,
    },

    // ==================== VOCABULARY (15 Questions) ====================
    {
        type: 'vocabulary',
        question: 'What is the synonym of \"benevolent\"?',
        options: ['mean', 'kind', 'lazy', 'brave'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'What is the antonym of \"abundant\"?',
        options: ['plentiful', 'scarce', 'plenty', 'sufficient'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'To \"procrastinate\" means to:',
        options: ['work hard', 'delay doing something', 'finish quickly', 'plan carefully'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'The company decided to ____ from the project due to financial issues.',
        options: ['withdraw', 'involve', 'engage', 'participate'],
        correctAnswer: 0,
    },
    {
        type: 'vocabulary',
        question: 'What is a synonym for \"abundant\"?',
        options: ['scarce', 'plentiful', 'minimal', 'rare'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'He decided to \"call off\" the meeting. This means to:',
        options: ['postpone', 'cancel', 'attend', 'organize'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'The speech was so ____ that everyone was moved to tears.',
        options: ['mundane', 'poignant', 'superficial', 'trivial'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'Which phrasal verb means \"to improve\"?',
        options: ['get down', 'get along', 'get over', 'get ahead'],
        correctAnswer: 3,
    },
    {
        type: 'vocabulary',
        question: '\"To ameliorate\" means to:',
        options: ['worsen', 'improve', 'ignore', 'delay'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'The film was criticized for being too ____ and lacking depth.',
        options: ['profound', 'superficial', 'complex', 'meaningful'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'To \"put up with\" someone means to ____ them.',
        options: ['punish', 'tolerate', 'help', 'promote'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'Which word means the opposite of \"eloquent\"?',
        options: ['articulate', 'inarticulate', 'fluent', 'expressive'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'Her ____ attitude towards life made her popular among friends.',
        options: ['pessimistic', 'cynical', 'optimistic', 'gloomy'],
        correctAnswer: 2,
    },
    {
        type: 'vocabulary',
        question: 'To \"give up\" means to:',
        options: ['offer', 'surrender', 'continue', 'begin'],
        correctAnswer: 1,
    },
    {
        type: 'vocabulary',
        question: 'The ____ of the ancient civilization amazed archaeologists.',
        options: ['destruction', 'legacy', 'absence', 'poverty'],
        correctAnswer: 1,
    },

    // ==================== READING (10 Questions) ====================
    {
        type: 'reading',
        passage: 'The Amazon rainforest, often referred to as the \"lungs of the Earth,\" covers approximately 5.5 million square kilometers across nine countries. It is home to about 10% of all species on Earth, making it the most biodiverse place on the planet. However, deforestation poses a significant threat to this ecosystem. Approximately 137 species become extinct every single day due to rainforest destruction. Indigenous communities have lived in harmony with the forest for thousands of years, and their knowledge has proven invaluable for conservation efforts. Scientists believe that protecting the rainforest is crucial not only for biodiversity but also for combating climate change, as the forest acts as a carbon sink.',
        question: 'What is the primary function of the Amazon rainforest mentioned in the passage?',
        options: ['To provide natural resources for international trade', 'To act as the \"lungs of the Earth\"', 'To serve as a military base', 'To generate electricity'],
        correctAnswer: 1,
    },
    {
        type: 'reading',
        passage: 'The Amazon rainforest, often referred to as the \"lungs of the Earth,\" covers approximately 5.5 million square kilometers across nine countries. It is home to about 10% of all species on Earth, making it the most biodiverse place on the planet. However, deforestation poses a significant threat to this ecosystem. Approximately 137 species become extinct every single day due to rainforest destruction. Indigenous communities have lived in harmony with the forest for thousands of years, and their knowledge has proven invaluable for conservation efforts. Scientists believe that protecting the rainforest is crucial not only for biodiversity but also for combating climate change, as the forest acts as a carbon sink.',
        question: 'How many species become extinct daily according to the passage?',
        options: ['About 100', 'About 137', 'About 500', 'About 1000'],
        correctAnswer: 1,
    },
    {
        type: 'reading',
        passage: 'The Amazon rainforest, often referred to as the \"lungs of the Earth,\" covers approximately 5.5 million square kilometers across nine countries. It is home to about 10% of all species on Earth, making it the most biodiverse place on the planet. However, deforestation poses a significant threat to this ecosystem. Approximately 137 species become extinct every single day due to rainforest destruction. Indigenous communities have lived in harmony with the forest for thousands of years, and their knowledge has proven invaluable for conservation efforts. Scientists believe that protecting the rainforest is crucial not only for biodiversity but also for combating climate change, as the forest acts as a carbon sink.',
        question: 'What role do indigenous communities play in the Amazon?',
        options: ['They exploit the forest\\'s resources', 'They have lived in harmony with the forest and possess valuable conservation knowledge', 'They are responsible for deforestation', 'They study the climate'],
        correctAnswer: 1,
    },
    {
        type: 'reading',
        passage: 'The Amazon rainforest, often referred to as the \"lungs of the Earth,\" covers approximately 5.5 million square kilometers across nine countries. It is home to about 10% of all species on Earth, making it the most biodiverse place on the planet. However, deforestation poses a significant threat to this ecosystem. Approximately 137 species become extinct every single day due to rainforest destruction. Indigenous communities have lived in harmony with the forest for thousands of years, and their knowledge has proven invaluable for conservation efforts. Scientists believe that protecting the rainforest is crucial not only for biodiversity but also for combating climate change, as the forest acts as a carbon sink.',
        question: 'Why is protecting the rainforest important for climate change?',
        options: ['It produces oxygen', 'It prevents hurricanes', 'It acts as a carbon sink', 'It regulates ocean temperatures'],
        correctAnswer: 2,
    },
    {
        type: 'reading',
        passage: 'The Amazon rainforest, often referred to as the \"lungs of the Earth,\" covers approximately 5.5 million square kilometers across nine countries. It is home to about 10% of all species on Earth, making it the most biodiverse place on the planet. However, deforestation poses a significant threat to this ecosystem. Approximately 137 species become extinct every single day due to rainforest destruction. Indigenous communities have lived in harmony with the forest for thousands of years, and their knowledge has proven invaluable for conservation efforts. Scientists believe that protecting the rainforest is crucial not only for biodiversity but also for combating climate change, as the forest acts as a carbon sink.',
        question: 'What percentage of Earth\\'s species live in the Amazon?',
        options: ['5%', '10%', '15%', '20%'],
        correctAnswer: 1,
    },
    {
        type: 'reading',
        passage: 'Artificial Intelligence (AI) is rapidly transforming industries worldwide. In healthcare, AI algorithms can now detect certain cancers more accurately than human radiologists. In finance, machine learning models predict market trends and detect fraudulent transactions. In education, AI-powered platforms personalize learning experiences for students. However, the rapid advancement of AI raises important ethical questions. Issues such as data privacy, algorithmic bias, and job displacement have become central concerns. Experts argue that developing strong regulations and ethical frameworks is essential to ensure AI benefits society while minimizing potential harms. The future of AI depends not only on technological innovation but also on responsible development and deployment.',
        question: 'In healthcare, what advantage do AI algorithms have over human radiologists?',
        options: ['They are cheaper', 'They work faster', 'They can detect certain cancers more accurately', 'They require less training'],
        correctAnswer: 2,
    },
    {
        type: 'reading',
        passage: 'Artificial Intelligence (AI) is rapidly transforming industries worldwide. In healthcare, AI algorithms can now detect certain cancers more accurately than human radiologists. In finance, machine learning models predict market trends and detect fraudulent transactions. In education, AI-powered platforms personalize learning experiences for students. However, the rapid advancement of AI raises important ethical questions. Issues such as data privacy, algorithmic bias, and job displacement have become central concerns. Experts argue that developing strong regulations and ethical frameworks is essential to ensure AI benefits society while minimizing potential harms. The future of AI depends not only on technological innovation but also on responsible development and deployment.',
        question: 'Which of the following is NOT mentioned as an application of AI in the passage?',
        options: ['Healthcare', 'Finance', 'Education', 'Agriculture'],
        correctAnswer: 3,
    },
    {
        type: 'reading',
        passage: 'Artificial Intelligence (AI) is rapidly transforming industries worldwide. In healthcare, AI algorithms can now detect certain cancers more accurately than human radiologists. In finance, machine learning models predict market trends and detect fraudulent transactions. In education, AI-powered platforms personalize learning experiences for students. However, the rapid advancement of AI raises important ethical questions. Issues such as data privacy, algorithmic bias, and job displacement have become central concerns. Experts argue that developing strong regulations and ethical frameworks is essential to ensure AI benefits society while minimizing potential harms. The future of AI depends not only on technological innovation but also on responsible development and deployment.',
        question: 'What is the main concern raised about AI advancement?',
        options: ['It\\'s too expensive', 'Ethical questions about data privacy, bias, and job displacement', 'It\\'s not effective enough', 'It\\'s only useful for large companies'],
        correctAnswer: 1,
    },
    {
        type: 'reading',
        passage: 'Artificial Intelligence (AI) is rapidly transforming industries worldwide. In healthcare, AI algorithms can now detect certain cancers more accurately than human radiologists. In finance, machine learning models predict market trends and detect fraudulent transactions. In education, AI-powered platforms personalize learning experiences for students. However, the rapid advancement of AI raises important ethical questions. Issues such as data privacy, algorithmic bias, and job displacement have become central concerns. Experts argue that developing strong regulations and ethical frameworks is essential to ensure AI benefits society while minimizing potential harms. The future of AI depends not only on technological innovation but also on responsible development and deployment.',
        question: 'According to the passage, what is essential for AI\\'s positive future?',
        options: ['Eliminating all regulations', 'Stopping AI development', 'Developing strong regulations and ethical frameworks', 'Using AI only in healthcare'],
        correctAnswer: 2,
    },
    {
        type: 'reading',
        passage: 'Artificial Intelligence (AI) is rapidly transforming industries worldwide. In healthcare, AI algorithms can now detect certain cancers more accurately than human radiologists. In finance, machine learning models predict market trends and detect fraudulent transactions. In education, AI-powered platforms personalize learning experiences for students. However, the rapid advancement of AI raises important ethical questions. Issues such as data privacy, algorithmic bias, and job displacement have become central concerns. Experts argue that developing strong regulations and ethical frameworks is essential to ensure AI benefits society while minimizing potential harms. The future of AI depends not only on technological innovation but also on responsible development and deployment.',
        question: 'What does the passage suggest about the future of AI?',
        options: ['It depends only on technological innovation', 'It depends on both innovation and responsible development', 'AI will not be used in the future', 'Only wealthy countries will benefit from AI'],
        correctAnswer: 1,
    },

    // ==================== WRITING (1 Task) ====================
    {
        type: 'writing',
        question: 'Write an essay (80-120 words) on the following topic: \"How technology has changed the way we communicate\"\n\nInclude:\n- How communication has changed\n- Benefits and challenges\n- Your personal opinion',
        options: [],
        correctAnswer: -1,
    },
];